### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Steezy63** [fluffyst/ckSurf-mapchooser#2]
L 11/13/2017 - 18:16:43: SourceMod error session started
L 11/13/2017 - 18:16:43: Info (map "surf_calycate2") (file "errors_20171113.log")
L 11/13/2017 - 18:16:43: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 11/13/2017 - 18:16:43: [SM] Blaming: mapchooser.smx
L 11/13/2017 - 18:16:43: [SM] Call stack trace:
L 11/13/2017 - 18:16:43: [SM]   [0] GetConVarBool
L 11/13/2017 - 18:16:43: [SM]   [1] Line 1289, mapchooser.sp::SelectMapList
L 11/13/2017 - 18:16:43: [SM]   [2] Line 250, mapchooser.sp::OnConfigsExecuted
L 11/13/2017 - 18:17:06: Error log file session closed.
L 11/13/2017 - 18:17:06: SourceMod error session started
L 11/13/2017 - 18:17:06: Info (map "surf_calycate2") (file "errors_20171113.log")
L 11/13/2017 - 18:17:06: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 11/13/2017 - 18:17:06: [SM] Blaming: mapchooser.smx
L 11/13/2017 - 18:17:06: [SM] Call stack trace:
L 11/13/2017 - 18:17:06: [SM]   [0] GetConVarBool
L 11/13/2017 - 18:17:06: [SM]   [1] Line 1289, mapchooser.sp::SelectMapList
L 11/13/2017 - 18:17:06: [SM]   [2] Line 250, mapchooser.sp::OnConfigsExecuted

**Comment by fluffyst** [comment]
this should be fixed

**Comment by Steezy63** [comment]
Error is fixed 
!nominate shows only Tier 1 Maps for me ...also !rtv 

sm_server_tier 1.6
sm_cksurf_type 1
sm_mapchooser_show_all_maps 0

**Comment by fluffyst** [comment]
make sure sm_server_tier isn't 1.0 in cfg/nominations.cfg

**Comment by Steezy63** [comment]
Fixed ...my bad sorry 

thanks for your hard work :)

**Comment by fluffyst** [comment]
my bad actually, I forgot it auto-generates the nominations.cfg file, updated the readme!

**Comment by Steezy63** [comment]
name of the file is "cksurf_nominations.cfg"

**Comment by fluffyst** [comment]
ah, I don't remember changing that, thanks.
